#!/bin/bash

echo "Configuring instanthpi.ca domain for Netlify deployment"
echo "======================================================="

# Site details
SITE_NAME="instanthpi-medical"
CUSTOM_DOMAIN="instanthpi.ca"
NETLIFY_TOKEN="nfp_MHncB8Hr3wj4T2mrbFRDoNjbcB1W9SPve0b1"

echo ""
echo "IMPORTANT: DNS Configuration Required"
echo "======================================"
echo ""
echo "To connect instanthpi.ca to your Netlify site, you need to:"
echo ""
echo "1. Log into your domain registrar (where you purchased instanthpi.ca)"
echo ""
echo "2. Update your DNS settings with ONE of these options:"
echo ""
echo "   OPTION A - Using CNAME (Recommended for subdomains like www):"
echo "   ----------------------------------------------------------------"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: instanthpi-medical.netlify.app"
echo ""
echo "   OPTION B - Using A Records (For apex domain instanthpi.ca):"
echo "   ----------------------------------------------------------------"
echo "   Type: A"
echo "   Name: @ (or leave blank)"
echo "   Value: 75.2.60.5"
echo ""
echo "   Alternative Netlify Load Balancer IP (if needed):"
echo "   Type: A"
echo "   Name: @ (or leave blank)"
echo "   Value: 104.198.14.52"
echo ""
echo "   OPTION C - Using Netlify DNS (Easiest - Full DNS Management):"
echo "   ----------------------------------------------------------------"
echo "   Change your domain's nameservers to:"
echo "   - dns1.p01.nsone.net"
echo "   - dns2.p01.nsone.net"
echo "   - dns3.p01.nsone.net"
echo "   - dns4.p01.nsone.net"
echo ""
echo "3. The DNS propagation can take 24-48 hours, but usually works within 1-2 hours"
echo ""
echo "4. Once DNS is configured, Netlify will automatically:"
echo "   - Detect the domain"
echo "   - Provision an SSL certificate"
echo "   - Enable HTTPS"
echo ""
echo "Your current site URLs:"
echo "========================"
echo "Netlify URL: https://instanthpi-medical.netlify.app"
echo "Custom Domain (after DNS): https://instanthpi.ca"
echo ""
echo "To verify domain setup in Netlify:"
echo "1. Visit: https://app.netlify.com/projects/instanthpi-medical/domain-management"
echo "2. Click 'Add a custom domain'"
echo "3. Enter: instanthpi.ca"
echo "4. Follow the DNS configuration instructions"
echo ""
echo "Testing your domain (after DNS configuration):"
echo "==============================================="
echo "You can test if DNS is working with these commands:"
echo ""
echo "  nslookup instanthpi.ca"
echo "  dig instanthpi.ca"
echo "  curl -I https://instanthpi.ca"
echo ""

# Try to add domain via API (may require manual confirmation)
echo "Attempting to add domain via API..."
curl -X PUT "https://api.netlify.com/api/v1/sites/${SITE_NAME}.netlify.app" \
  -H "Authorization: Bearer ${NETLIFY_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"custom_domain\": \"${CUSTOM_DOMAIN}\"}" 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Note: Domain must be added manually in Netlify admin panel"

echo ""
echo "======================================================="
echo "Next Steps:"
echo "1. Configure DNS as shown above"
echo "2. Visit https://app.netlify.com/projects/instanthpi-medical/domain-management"
echo "3. Add instanthpi.ca as custom domain"
echo "4. Wait for DNS propagation and SSL certificate"
echo "======================================================="