-- Create 5 diverse test patient cases for doctor testing
-- Each case has different medical scenarios to test the AI generation

-- Case 1: Chest Pain (Cardiac concern)
INSERT INTO consultations (
  id,
  patient_id,
  chief_complaint,
  symptoms,
  severity,
  triage_level,
  status,
  age,
  gender,
  problem_start_date,
  specific_trigger,
  symptom_location,
  symptom_description,
  symptom_aggravators,
  symptom_relievers,
  symptom_progression,
  selected_symptoms,
  treatments_attempted,
  treatment_effectiveness,
  chronic_conditions,
  medication_allergies,
  pregnancy_status,
  additional_notes,
  created_at
) VALUES (
  gen_random_uuid(),
  'C1H3S7P4A9',
  'Douleur thoracique',
  'Douleur thoracique rétrosternale, palpitations, essoufflement',
  '8',
  'P2',
  'pending',
  '45',
  'Homme',
  'Il y a 2 heures',
  'Effort physique',
  'Rétrosternal, irradiant vers le bras gauche',
  'Douleur en pression, sensation de serrement',
  'Effort, respiration profonde',
  'Repos, position assise',
  'Apparition brutale, stable depuis',
  '["Palpitations", "Essoufflement", "Sueurs froides"]',
  'Paracétamol 1000mg',
  'Aucune amélioration',
  'Hypertension artérielle, diabète type 2',
  'Aucune allergie connue',
  'Non applicable',
  'Patient fumeur, 20 paquets-années',
  NOW()
);

-- Case 2: Migraine (Neurological)
INSERT INTO consultations (
  id,
  patient_id,
  chief_complaint,
  symptoms,
  severity,
  triage_level,
  status,
  age,
  gender,
  problem_start_date,
  specific_trigger,
  symptom_location,
  symptom_description,
  symptom_aggravators,
  symptom_relievers,
  symptom_progression,
  selected_symptoms,
  treatments_attempted,
  treatment_effectiveness,
  chronic_conditions,
  medication_allergies,
  pregnancy_status,
  additional_notes,
  created_at
) VALUES (
  gen_random_uuid(),
  'M2I8G9R3A1',
  'Céphalée sévère',
  'Céphalée pulsatile, photophobie, nausées',
  '7',
  'P3',
  'pending',
  '32',
  'Femme',
  'Il y a 6 heures',
  'Stress au travail',
  'Fronto-temporale droite',
  'Douleur pulsatile, battements',
  'Lumière, bruit, mouvement',
  'Obscurité, repos, sommeil',
  'Intensité croissante depuis le matin',
  '["Photophobie", "Nausées", "Vomissements"]',
  'Ibuprofène 400mg, sommeil',
  'Légère amélioration avec le sommeil',
  'Migraines chroniques',
  'Aspirine (urticaire)',
  'Non enceinte',
  'Antécédents familiaux de migraines',
  NOW()
);

-- Case 3: Abdominal Pain (Gastrointestinal)
INSERT INTO consultations (
  id,
  patient_id,
  chief_complaint,
  symptoms,
  severity,
  triage_level,
  status,
  age,
  gender,
  problem_start_date,
  specific_trigger,
  symptom_location,
  symptom_description,
  symptom_aggravators,
  symptom_relievers,
  symptom_progression,
  selected_symptoms,
  treatments_attempted,
  treatment_effectiveness,
  chronic_conditions,
  medication_allergies,
  pregnancy_status,
  additional_notes,
  created_at
) VALUES (
  gen_random_uuid(),
  'A3B5D9O7M2',
  'Douleur abdominale',
  'Douleur abdominale, nausées, perte d''appétit',
  '6',
  'P3',
  'pending',
  '28',
  'Femme',
  'Il y a 12 heures',
  'Repas copieux hier soir',
  'Épigastre, irradiant vers le dos',
  'Douleur en crampes, sensation de brûlure',
  'Alimentation, position couchée',
  'Position assise, jeûne',
  'Douleur constante avec pics',
  '["Nausées", "Perte d''appétit", "Ballonnements"]',
  'Antiacides, tisane à la menthe',
  'Légère amélioration',
  'Reflux gastro-œsophagien',
  'Aucune allergie connue',
  'Non enceinte',
  'Consommation d''alcool modérée',
  NOW()
);

-- Case 4: Back Pain (Musculoskeletal)
INSERT INTO consultations (
  id,
  patient_id,
  chief_complaint,
  symptoms,
  severity,
  triage_level,
  status,
  age,
  gender,
  problem_start_date,
  specific_trigger,
  symptom_location,
  symptom_description,
  symptom_aggravators,
  symptom_relievers,
  symptom_progression,
  selected_symptoms,
  treatments_attempted,
  treatment_effectiveness,
  chronic_conditions,
  medication_allergies,
  pregnancy_status,
  additional_notes,
  created_at
) VALUES (
  gen_random_uuid(),
  'B4A8C6K1P5',
  'Lombalgie aiguë',
  'Douleur lombaire, raideur, difficulté à bouger',
  '5',
  'P4',
  'pending',
  '55',
  'Homme',
  'Il y a 3 jours',
  'Soulèvement de charges lourdes',
  'Lombaire bas, irradiant vers la fesse droite',
  'Douleur mécanique, raideur matinale',
  'Mouvement, position debout prolongée',
  'Repos, chaleur, position couchée',
  'Amélioration progressive avec le repos',
  '["Raideur", "Difficulté à se pencher", "Spasmes musculaires"]',
  'Diclofénac gel, chaleur locale',
  'Amélioration partielle',
  'Lombalgie chronique, arthrose',
  'Aucune allergie connue',
  'Non applicable',
  'Travail physique, surpoids',
  NOW()
);

-- Case 5: Respiratory Symptoms (Pulmonary)
INSERT INTO consultations (
  id,
  patient_id,
  chief_complaint,
  symptoms,
  severity,
  triage_level,
  status,
  age,
  gender,
  problem_start_date,
  specific_trigger,
  symptom_location,
  symptom_description,
  symptom_aggravators,
  symptom_relievers,
  symptom_progression,
  selected_symptoms,
  treatments_attempted,
  treatment_effectiveness,
  chronic_conditions,
  medication_allergies,
  pregnancy_status,
  additional_notes,
  created_at
) VALUES (
  gen_random_uuid(),
  'R5E8S9P2I6',
  'Toux persistante',
  'Toux sèche, essoufflement, fatigue',
  '4',
  'P4',
  'pending',
  '67',
  'Femme',
  'Il y a 1 semaine',
  'Exposition à la poussière',
  'Thorax, sensation d''oppression',
  'Toux sèche, irritante, nocturne',
  'Position couchée, air froid',
  'Position assise, humidité',
  'Toux nocturne plus fréquente',
  '["Essoufflement", "Fatigue", "Perte d''appétit"]',
  'Sirop antitussif, humidificateur',
  'Aucune amélioration',
  'Asthme, hypertension',
  'Pénicilline (éruption cutanée)',
  'Non applicable',
  'Ex-fumeuse, arrêt il y a 5 ans',
  NOW()
);
