#!/bin/bash

echo "==================================="
echo "SUPABASE DEPLOYMENT INSTRUCTIONS"
echo "==================================="
echo ""
echo "STEP 1: Create Supabase Project"
echo "--------------------------------"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Enter these details:"
echo "   - Name: instanthpi-medical"
echo "   - Password: InstantHPI2024Secure!"
echo "   - Region: US East (N. Virginia)"
echo ""
echo "STEP 2: Get Your Credentials"
echo "-----------------------------"
echo "After project creation, go to Settings > API and copy:"
echo "- Project URL"
echo "- anon/public key"
echo "- service_role key"
echo ""
echo "STEP 3: Update Environment File"
echo "--------------------------------"
echo "Edit .env.production with your Supabase credentials"
echo ""
echo "STEP 4: Apply Database Schema"
echo "------------------------------"
echo "1. Go to SQL Editor in Supabase Dashboard"
echo "2. Click 'New Query'"
echo "3. Copy contents from: supabase/migrations/001_initial_schema.sql"
echo "4. Run the query"
echo ""
echo "STEP 5: Deploy Edge Functions"
echo "------------------------------"
echo "Run: npx supabase functions deploy handle-messages"
echo ""
echo "STEP 6: Enable Authentication"
echo "------------------------------"
echo "1. Go to Authentication > Providers"
echo "2. Enable Email provider"
echo "3. Set up your admin user"
echo ""
echo "STEP 7: Deploy to Production"
echo "-----------------------------"
echo "Option A - Vercel:"
echo "  1. Push code to GitHub"
echo "  2. Import project in Vercel"
echo "  3. Add environment variables"
echo "  4. Deploy"
echo ""
echo "Option B - Railway:"
echo "  1. Push code to GitHub"
echo "  2. Create new project in Railway"
echo "  3. Add environment variables"
echo "  4. Deploy"
echo ""
echo "Option C - Supabase Edge Functions:"
echo "  1. Deploy all functions with: npx supabase functions deploy"
echo ""
echo "==================================="
echo "Your application will be fully online and secure!"
echo "Only you will have access with proper authentication."
echo "===================================="